package primitive

import (
	"errors"
	"flag"
	"fmt"
	"github.com/google/uuid"
	"github.com/mini-e-commerce-microservice/product-service/internal/util"
	"time"
)

type PresignedFileUpload struct {
	Identifier       string
	OriginalFileName string
	MimeType         MimeType
	Size             int64
	ChecksumSHA256   string

	// Generated by Backend
	GeneratedFileName string
	Extension         string
}

type PresignedFileUploadOutput struct {
	Identifier      string
	UploadURL       string
	UploadExpiredAt time.Time
	MinioFormData   map[string]string
}

type NewPresignedFileUploadInput struct {
	Identifier       string
	OriginalFileName string
	MimeType         MimeType
	Size             int64
	ChecksumSHA256   string
}

func NewPresignedFileUpload(input NewPresignedFileUploadInput) (output PresignedFileUpload, err error) {
	if !input.MimeType.IsValid() {
		return output, errors.New("mime type " + string(input.MimeType) + " is not allowed")
	}
	if util.BytesToMB(input.Size) > input.MimeType.MediaMaxSize() {
		return output, fmt.Errorf("file size %d exceeds the maximum allowed size %d for media type %s", input.Size, int64(input.MimeType.MediaMaxSize()), input.MimeType)
	}
	extension := input.MimeType.Extension()
	uuidString := uuid.New().String()
	generatedFileName := uuidString + extension
	if flag.Lookup("test.v") != nil {
		generatedFileName = input.OriginalFileName
	}
	return PresignedFileUpload{
		Identifier:        input.Identifier,
		OriginalFileName:  input.OriginalFileName,
		MimeType:          input.MimeType,
		Size:              input.Size,
		ChecksumSHA256:    input.ChecksumSHA256,
		GeneratedFileName: generatedFileName,
		Extension:         extension,
	}, nil
}
